//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 MKCardSampleApp.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MKCARDSAMPLEAPP_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SCPORTCAPTURE        129
#define IDD_DIALOG_VIDEOVIEW            130
#define IDD_DIALOG_REGISTER             131
#define IDD_DIALOG_SCPORTSEND           132
#define IDD_DIALOG_AUDIO_CAPTURE        133
#define IDC_MKCARDDLG_STATIC_SOFTWAREINFO 1001
#define IDC_MKCARDDLG_STATIC_SUB_TYPE   1002
#define IDC_MKCARDDLG_STATIC_HARDWAREINFO 1003
#define IDC_MKCARDDLG_STATIC_TEMPERATURE 1004
#define IDC_MKCARDDLG_LIST_CARDLIST     1005
#define IDC_MKCARDDLG_LIST_PORTLIST     1006
#define IDC_MKCARDDLG_BTN_OPENCARD      1007
#define IDC_MKCARDDLG_BTN_CLOSECARD     1008
#define IDC_MKCARDDLG_BTN_REGISTER      1009
#define IDC_MKCARDDLG_BTN_OPEN_PORTCAP  1010
#define IDC_MKCARDDLG_BTN_OPEN_PORTSEND 1011
#define IDC_STATIC_IMAGEVIEW            1030
#define IDC_BUTTON_VIEW                 1050
#define IDC_CHECK_PLAYAUDIO             1051
#define IDC_EDIT_SIGNAL_INFO            1053
#define IDC_BUTTON_GETMEDIAINFO         1054
#define IDC_BUTTON_BEGINCAPTURE         1056
#define IDC_BUTTON_STOPCAPTURE          1057
#define IDC_STATIC_FRAME_COUNTER        1058
#define IDC_REGISTERDLG_BTN_READ        1110
#define IDC_REGISTERDLG_BTN_WRITE       1111
#define IDC_REGISTERDLG_EDIT_ADDRESS    1112
#define IDC_REGISTERDLG_EDIT_VALUE      1113
#define IDC_REGISTERDLG_EDIT_BAR        1114
#define IDC_SENDDLG_BTN_BEGINSEND       1170
#define IDC_SENDDLG_BTN_STOPSEND        1171
#define IDC_SENDDLG_COMBO_STANDARD      1172
#define IDC_SENDDLG_STATIC_TIMEINFO     1182

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1184
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
